#!/usr/bin/env bash

version=$(jq .version manifest.json -r)
dir="dist/pigquery-$version"

echo "Building PigQuery version $version"

rm -rf dist
mkdir -p "$dir"

cp manifest.json "$dir/"
cp LICENSE.txt "$dir/"
cp -R src "$dir/"
cp -R icons "$dir/"
cp -R lib "$dir/"
cp -R _locales "$dir/"

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --pack-extension="$PWD/$dir" --pack-extension-key="$PWD/privatekey.pem"
