#!/usr/bin/env bash

version=$(jq .version manifest.json -r)
commit=$(git rev-parse HEAD)
dir="dist/pigquery-$version"

echo "Building PigQuery version $version ($commit)"

rm -rf dist
mkdir -p "$dir"

# Remove management permission from manifest.json. It is only needed for development.
jq 'del(.permissions[] | select(. == "management" or . == "tabs"))' manifest.json > "$dir/manifest.json"
cp LICENSE.txt "$dir/"
cp -R src "$dir/"
cp -R icons "$dir/"
cp -R lib "$dir/"
cp -R _locales "$dir/"

echo "$commit" > "$dir/commit.txt"

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --pack-extension="$PWD/$dir" --pack-extension-key="$PWD/privatekey.pem"
