#!/usr/bin/env bash

version=$(jq .version manifest.json -r)
commit=$(git rev-parse HEAD)
packageDir="package/pigquery-$version"

echo "Building PigQuery version $version ($commit)"

# Build the bundled JS files
echo "Building bundled JS..."
NODE_ENV=production node build.js

rm -rf package
mkdir -p "$packageDir"

# Remove dev-only permissions from manifest.json. They are only needed for development.
jq 'del(.permissions[] | select(. == "management" or . == "tabs" or . == "scripting"))' manifest.json > "$packageDir/manifest.json"
cp LICENSE.txt "$packageDir/"
cp -R dist "$packageDir/"
cp -R icons-prod "$packageDir/icons"
cp -R _locales "$packageDir/"

echo "$commit" > "$packageDir/commit.txt"

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --pack-extension="$PWD/$packageDir" --pack-extension-key="$PWD/privatekey"
