#!/usr/bin/env bash

# Setup development directory with symlinks for rapid development
# Only needs to be run once or when new directories/files are added

dev_dir="dev"

rm -rf "$dev_dir"
mkdir -p "$dev_dir"
ln -s ../src "$dev_dir/src"
ln -s ../icons "$dev_dir/icons"
ln -s ../lib "$dev_dir/lib"
ln -s ../_locales "$dev_dir/_locales"
ln -s ../manifest.json "$dev_dir/manifest.json"
ln -s ../LICENSE.txt "$dev_dir/LICENSE.txt"
